<a href="https://colab.research.google.com/github/financieras/math_for_ai/blob/main/220_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conceptos fundamentales de matrices

## 1. Definición de matriz

Una matriz es una estructura rectangular de datos ordenados en filas y columnas. Matemáticamente, una matriz se puede representar como:

$$A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{pmatrix}$$

Donde:
- $a_{ij}$ representa el elemento ubicado en la fila $i$ y columna $j$.
- $m$ es el número de filas.
- $n$ es el número de columnas.
- La matriz anterior es de dimensión  $ m \times n $, con $m$ filas y $n$ columnas.

En Python, podemos representar matrices utilizando la biblioteca NumPy:

In [ ]:
import numpy as np

# Crear una matriz de 3x3
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matriz A:")
print(A)

Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Acceder a los elementos de una matriz
En Python podemos acceder a elementos específicos de una matriz utilizando índices.

In [ ]:
# Accediendo a elementos de la matriz
print(f"Elemento A[0,0]: {A[0,0]}")  # Equivalente a a_{11}
print(f"Elemento A[1,2]: {A[1,2]}")  # Equivalente a a_{23}

# Obteniendo dimensiones
filas, columnas = A.shape
print(f"Dimensiones de A: {filas}×{columnas}")
print(f"Número total de elementos: {A.size}")

Elemento A[0,0]: 1
Elemento A[1,2]: 6
Dimensiones de A: 3×3
Número total de elementos: 9


### Submatrices
Una submatriz es una porción de una matriz original.  
En Python, podemos extraer submatrices utilizando el sistema de indexación de NumPy:

In [ ]:
# Extraer una submatriz (las primeras 2 filas y 2 columnas)
submatriz = A[0:2, 0:2]
print("Submatriz de A (primeras 2 filas y columnas):")
print(submatriz)

Submatriz de A (primeras 2 filas y columnas):
[[1 2]
 [4 5]]


## 2. Tipos de Matrices

Existen varios tipos de matrices según su estructura o propiedades:

1. **Matriz cuadrada**: $m = n$ (mismo número de filas y columnas).
2. **Matriz fila**: $m = 1$ (una sola fila).
3. **Matriz columna**: n = 1 (una sola columna).
4. **Matriz nula**: Todos sus elementos son 0.
5. **Matriz identidad**: Matriz cuadrada con 1s en la diagonal principal y 0s fuera de ella, denotada $I$.
6. **Matriz diagonal**: Solo tiene elementos en la diagonal principal.

### Ejemplos

$$
\text{Matriz cuadrada } (3 \times 3) \quad \rightarrow \quad
M = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

$$
\text{Matriz identidad } (3 \times 3) \quad \rightarrow \quad
I_3 = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

$$
\text{Matriz fila } (1 \times 3) \quad \rightarrow \quad
F = \begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
$$

$$
\text{Matriz columna } (3 \times 1) \quad \rightarrow \quad
C = \begin{bmatrix}
4 \\
5 \\
6
\end{bmatrix}
$$

$$
\text{Matriz nula } (2 \times 2) \quad \rightarrow \quad
N = \begin{bmatrix}
0 & 0 \\
0 & 0
\end{bmatrix}
$$


In [ ]:
# Matriz cuadrada 3x3
cuadrada = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print("Matriz cuadrada 3x3:")
print(cuadrada)

# Matriz identidad 3x3
identidad = np.eye(3)
print("\nMatriz identidad 3x3:")
print(identidad)

# Matriz fila y columna
fila = np.array([[1, 2, 3]])
columna = np.array([[4], [5], [6]])
print("\nMatriz fila (1x3):")
print(fila)
print("\nMatriz columna (3x1):")
print(columna)

# Matriz nula 2x2
nula = np.zeros((2, 2))
print("\nMatriz nula 2x2:")
print(nula)

Matriz cuadrada 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz identidad 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz fila (1x3):
[[1 2 3]]

Matriz columna (3x1):
[[4]
 [5]
 [6]]

Matriz nula 2x2:
[[0. 0.]
 [0. 0.]]


## 3. Operaciones Básicas con Matrices

### Suma y Resta
Dos matrices $A$ y $B$ de las mismas dimensiones se suman/restan elemento a elemento:
$$
C = A + B, \quad c_{ij} = a_{ij} + b_{ij}
$$

### Multiplicación por Escalar
Un escalar $k$ multiplica cada elemento de la matriz:
$$
C = kA, \quad c_{ij} = k \cdot a_{ij}
$$

In [ ]:
# Definimos dos matrices 2x2
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Suma
suma = A + B
print("Suma A + B:")
print(suma)

# Resta
resta = A - B
print("\nResta A - B:")
print(resta)

# Multiplicación por escalar (normalización simple)
k = 0.5
escalada = k * A
print("\nMultiplicación de A por escalar 0.5:")
print(escalada)

Suma A + B:
[[ 6  8]
 [10 12]]

Resta A - B:
[[-4 -4]
 [-4 -4]]

Multiplicación de A por escalar 0.5:
[[0.5 1. ]
 [1.5 2. ]]


## 4. Combinación Lineal

Una **combinación lineal** de vectores $ \mathbf{v_1}, \mathbf{v_2}, \ldots, \mathbf{v_n} $ es:
$$
\mathbf{w} = c_1 \mathbf{v_1} + c_2 \mathbf{v_2} + \cdots + c_n \mathbf{v_n}
$$
El espacio generado es el conjunto de todas las combinaciones lineales.

### Ejemplo
Para $ \mathbf{v_1} = [1, 0] $, $ \mathbf{v_2} = [0, 1] $:
$$
\mathbf{w} = 2 \mathbf{v_1} + 3 \mathbf{v_2} = [2, 3]
$$

In [ ]:
# Vectores base
v1 = np.array([1, 0])
v2 = np.array([0, 1])

# Combinación lineal
w = 2 * v1 + 3 * v2
print("Combinación lineal w:", w)

Combinación lineal w: [2 3]


## 5. Multiplicación de Matrices

La multiplicación de matrices $A$ (de $m \times p $) y $ B $ (de $p \times n$) produce una matriz $C$ de $m \times n$). El elemento $c_{ij}$ se calcula como:
$$
c_{ij} = \sum_{k=1}^{p} a_{ik} \cdot b_{kj}
$$

### Condición
Las columnas de $A$ deben igualar las filas de $B$.

### Aplicación en Deep Learning
- Capas lineales: $W \cdot X$, donde $W$ es la matriz de pesos y $X$ el vector de entrada.

### Ejemplo
$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad
B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}, \quad
A \cdot B = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}
$$


In [ ]:
# Matrices 2x2
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Multiplicación
C = np.dot(A, B)  # o también se puede usar:  A @ B
print("Multiplicación A · B:")
print(C)

# Ejemplo Deep Learning: Capa lineal
X = np.array([[0.1], [0.2]])  # Entrada (2 características)
W = np.array([[0.5, 0.3],     # Pesos (2 entradas, 2 salidas)
              [0.4, 0.6]])
salida = np.dot(W, X)
print("\nSalida de capa lineal W · X:")
print(salida)

print("\nUsando @ para multiplicar matrices:\n")
W@X

Multiplicación A · B:
[[19 22]
 [43 50]]

Salida de capa lineal W · X:
[[0.11]
 [0.16]]

Usando @ para multiplicar matrices:



array([[0.11],
       [0.16]])

## 6. Transpuesta de una Matriz

La **transpuesta** de una matriz $A$, denotada $A^T$, intercambia filas por columnas:
$$
(A^T)_{ij} = A_{ji}
$$

### Propiedades
- $(A^T)^T = A$
- $(A + B)^T = A^T + B^T$

### Ejemplo
$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}, \quad
A^T = \begin{bmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \end{bmatrix}
$$

In [ ]:
# Matriz 3x2
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Transpuesta
A_T = A.T  # o np.transpose(A)
print("Matriz A:")
print(A)
print("\nTranspuesta A^T:")
print(A_T)

# Ejemplo en IA: Producto X^T · X
X = np.array([[0.1, 0.5],
              [0.2, 0.3]])
X_T = X.T
resultado = np.dot(X_T, X)
print("\nProducto X^T · X (covarianza aproximada):")
print(resultado)

Matriz A:
[[1 2]
 [3 4]
 [5 6]]

Transpuesta A^T:
[[1 3 5]
 [2 4 6]]

Producto X^T · X (covarianza aproximada):
[[0.05 0.11]
 [0.11 0.34]]


In [17]:
import numpy as np

# Matriz 3x3
A = np.array([[1, 2, -3],
              [-3, -1, -2],
              [-2, -1, 2]])

print("Matriz original:")
print(A)

print("\nMatriz transpuesta:")
print(A @ A.T)  # .T calcula la transpuesta

Matriz original:
[[ 1  2 -3]
 [-3 -1 -2]
 [-2 -1  2]]

Matriz transpuesta:
[[ 14   1 -10]
 [  1  14   3]
 [-10   3   9]]


### Matriz Simétrica
Al multiplicar una matriz $A$ por su Transpuesta $A^T$ se obtiene una matriz simétrica.

**En resumen:**
1. **Transpuesta**: Cambia filas por columnas
2. **A @ A^T**: Siempre produce una matriz simétrica
3. **Matriz simétrica**: Es como un espejo respecto a la diagonal principal

In [19]:
# El producto de A por su Transpuesta genera una matriz Simétrica
A @ A.T

array([[ 14,   1, -10],
       [  1,  14,   3],
       [-10,   3,   9]])

## 7. Traza de una Matriz

La **traza** de una matriz cuadrada $ A $ de orden $ n \times n $ es la suma de los elementos de su diagonal principal:
$$
\text{tr}(A) = a_{11} + a_{22} + \cdots + a_{nn} = \sum_{i=1}^{n} a_{ii}
$$

### Ejemplo
Para $ A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} $
$$
\text{tr}(A) = 1 + 5 + 9 = 15
$$

In [ ]:
# Matriz cuadrada
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Traza
traza = np.trace(A)
print("Traza de A:")
print(traza)

Traza de A:
15


## 8. Determinante

El **determinante** de una matriz cuadrada mide su "volumen" o si es invertible. Para una matriz $ 2 \times 2 $:
$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}, \quad \det(A) = ad - bc
$$

### Ejemplo
Para $ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $:
$$
\det(A) = 1 \cdot 4 - 2 \cdot 3 = 4 - 6 = -2
$$

In [ ]:
# Matriz 2x2
A = np.array([[1, 2],
              [3, 4]])

# Determinante
det = np.linalg.det(A)
print("Determinante de A:")
print(det)

Determinante de A:
-2.0000000000000004


## 9. Matriz Inversa

La **inversa** de una matriz cuadrada $ A $, denotada $ A^{-1} $, satisface:
$$
A \cdot A^{-1} = I
$$
Existe si $ \det(A) \neq 0 $. Para $ 2 \times 2 $:
$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}, \quad A^{-1} = \frac{1}{\det(A)} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

### Ejemplo
Para $ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $:
$$
A^{-1} = \frac{1}{-2} \begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix} = \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}
$$

Comprobación de que $A \cdot A^{-1} = I$

$$
A \cdot A^{-1} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \cdot \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} = I
$$


In [ ]:
# Matriz 2x2
A = np.array([[1, 2],
              [3, 4]])

# Inversa
A_inv = np.linalg.inv(A)
print("Inversa de A:")
print(A_inv)

# Verificación: A · A^-1 = I
print("\nVerificación A · A^(-1):")
resultado = np.dot(A, A_inv)
print(resultado)
print()

# Redondeamos a 10 decimales
resultado_redondeado = np.round(resultado, decimals=10)

print("Resultado de A · A^(-1) (redondeado):")
print(resultado_redondeado)

Inversa de A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Verificación A · A^(-1):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Resultado de A · A^(-1) (redondeado):
[[1. 0.]
 [0. 1.]]


## 10. Sistemas de Ecuaciones Lineales

Un sistema de ecuaciones lineales se escribe como $ A \mathbf{x} = \mathbf{b} $, donde $ A $ es la matriz de coeficientes, $ \mathbf{x} $ el vector de incógnitas y $ \mathbf{b} $ el vector de términos independientes.

### Ejemplo
$$
\begin{cases}
2x + 3y = 8 \\
x - y = 1
\end{cases}
$$
En forma matricial:
$$
\begin{bmatrix} 2 & 3 \\ 1 & -1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 8 \\ 1 \end{bmatrix}
$$

Solución con inversa: $$ \mathbf{x} = A^{-1} \cdot \mathbf{b} $$

**_Demostración_**

Partimos de la expresión matricial del sistema de ecuaciones y queremos despejar $\mathbf{x}$:

$$ A \mathbf{x} = \mathbf{b} $$

Premultiplicamos por la inversa de $A$ en ambos lados de la ecuación:

$$ A^{-1} \cdot A \cdot \mathbf{x} = A^{-1} \cdot \mathbf{b} $$

Sabemos que la inversa de $A$ por $A$ es la matriz identidad $I$.

$ A^{-1} \cdot A = I$

Nos ha quedado lo siguiente:

$$ I \cdot \mathbf{x} = A^{-1} \cdot \mathbf{b} $$

También sabemos que la matriz identidad $I$ por $\mathbf{x}$ es igual a $\mathbf{x}$.

$ I \cdot \mathbf{x} = x$

Con esto ya hemos conseguido despejar $\mathbf{x}$:

$$ \mathbf{x} = A^{-1} \cdot \mathbf{b} $$

In [ ]:
# Matriz de coeficientes y vector b
A = np.array([[2, 3],
              [1, -1]])
b = np.array([8, 1])

# Solución
#x = np.linalg.solve(A, b)  # o mejor con np.dot(np.linalg.inv(A), b)
x = np.dot(np.linalg.inv(A), b)

print("Solución x, y:")
print(x)

Solución x, y:
[2.2 1.2]


### **Ejemplo** con un Sistema de Ecuaciones 3×3
$$
\begin{cases}
-2x - 2y - z = 1 \\
-2x - y - 2z = -3 \\
-x - 2y + 3z = 7
\end{cases}
$$

### Forma Matricial:

$$
A\mathbf{x} = \mathbf{b} \quad \Rightarrow \quad
\begin{bmatrix} -2 & -2 & -1 \\ -2 & -1 & -2 \\ -1 & -2 & 3 \end{bmatrix}
\begin{bmatrix} x \\ y \\ z \end{bmatrix} =
\begin{bmatrix} 1 \\ -3 \\ 7 \end{bmatrix}
$$

Donde:

$$
A = \begin{bmatrix} -2 & -2 & -1 \\ -2 & -1 & -2 \\ -1 & -2 & 3 \end{bmatrix}, \quad
\mathbf{x} = \begin{bmatrix} x \\ y \\ z \end{bmatrix}, \quad
\mathbf{b} = \begin{bmatrix} 1 \\ -3 \\ 7 \end{bmatrix}
$$

El determinante de $A$ es $-5$ y su inversa es:

$$A^{-1} = \frac{1}{\det(A)} \cdot \text{adj}(A) = \frac{1}{-5} \cdot \begin{bmatrix}
-7 & 8 & 3 \\
8 & -7 & -2 \\
3 & -2 & -2
\end{bmatrix}
= \begin{bmatrix}
1.4 & -1.6 & -0.6 \\
-1.6 & 1.4 & 0.4 \\
-0.6 & 0.4 & 0.4
\end{bmatrix}$$

Solución matricial:

$$
\mathbf{x} = A^{-1} \cdot \mathbf{b} = \begin{bmatrix}
1.4 & -1.6 & -0.6 \\
-1.6 & 1.4 & 0.4 \\
-0.6 & 0.4 & 0.4
\end{bmatrix} \cdot \begin{bmatrix} 1 \\ -3 \\ 7 \end{bmatrix} = \begin{bmatrix} 2 \\ -3 \\ 1 \end{bmatrix}
\quad \Rightarrow \quad
\begin{cases}
x = 2 \\
y = -3 \\
z = 1
\end{cases}
$$

In [45]:
import numpy as np

A = np.array([[-2, -2, -1],
              [-2, -1, -2],
              [-1, -2,  3]])

b = np.array([1, -3, 7])

det_A = np.linalg.det(A)
x = np.linalg.solve(A, b)

print(f"Determinante de A: {det_A:.0f}")

print(f"\nSolución: x = {x[0]:.0f}, y = {x[1]:.0f}, z = {x[2]:.0f}")

Determinante de A: -5

Solución: x = 2, y = -3, z = 1


## 11. Forma Escalonada y Reducción

La **forma escalonada** de una matriz se obtiene aplicando eliminación gaussiana. Una matriz está en forma escalonada si:
- Las filas no nulas están sobre las filas de ceros.
- El primer elemento no nulo de cada fila (pivote) está a la derecha del pivote de la fila anterior.

### Ejemplo
Matriz $ A = \begin{bmatrix} 1 & 2 & 3 \\ 2 & 4 & 5 \end{bmatrix} $ se reduce a:
$$
\begin{bmatrix} 1 & 2 & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

Nota:  
NumPy no tiene una función directa para forma escalonada; usamos eliminación manual o bibliotecas como SymPy para ejemplos básicos

In [ ]:
# Usamos SymPy para reducción
from sympy import Matrix

A = Matrix([[1, 2, 3],
            [2, 4, 5]])
escalonada, _ = A.rref()
print("Forma escalonada de A:")
print(np.array(escalonada))

Forma escalonada de A:
[[1 2 0]
 [0 0 1]]


In [ ]:
A = Matrix([[1, 1, 1, 3],
            [1, 2, 3, 0],
            [1, 3, 4, -2]])
escalonada, _ = A.rref()
print("Forma escalonada de A:")
print(np.array(escalonada))

Forma escalonada de A:
[[1 0 0 5]
 [0 1 0 -1]
 [0 0 1 -1]]


## 12. Rango de una Matriz

El **rango** de una matriz es el número de filas (o columnas) linealmente independientes, equivalente al número de pivotes en su forma escalonada.

### Ejemplo
Para $ A = \begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix} $, la forma escalonada es:
$$
\begin{bmatrix} 1 & 2 \\ 0 & 0 \end{bmatrix}
$$
Rango = 1.

In [ ]:
# Matriz
A = np.array([[1, 2],
              [2, 4]])

# Rango
rango = np.linalg.matrix_rank(A)
print("Rango de A:", rango)

Rango de A: 1


## 13. Transformaciones Lineales

Una transformación lineal permite transformar un vector conservando sus propiedades fundamentales: suma y multiplicación por escalares.

Si tenemos un vector $\mathbf{x}$ y lo multiplicas por una matriz cuadrada $A$, obtenemos otro vector $T(\mathbf{x})$ que es una transformación lineal del original.

$$T(\mathbf{x}) = A\mathbf{x}$$

Esto significa que, cualquiera que sea la matriz $A$, la imagen de la suma de dos vectores es la suma de las imágenes, y multiplicar un vector por un escalar antes o después de la transformación da el mismo resultado.

Se cumplen estas dos propiedades de linealidad, para todo vector $\mathbf{u}, \mathbf{v}$ y escalar $c$:
1. $T(\mathbf{u} + \mathbf{v}) = T(\mathbf{u}) + T(\mathbf{v})$
2. $T(c\mathbf{u}) = cT(\mathbf{u})$

### Transformación Lineal de Rotación
Por ejemplo, vamos a ver cómo un vector en $\mathbb{R}^2$ se puede rotar 90º usando la matriz:

$$
A = \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}
$$

Si partimos del vector $\mathbf{x} = \begin{bmatrix}1 \\ 0 \end{bmatrix}$, su transformación es:

$$
T(\mathbf{x}) = A \mathbf{x} = \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}  \begin{bmatrix}1 \\ 0 \end{bmatrix} = \begin{bmatrix} 0 \\ 1 \end{bmatrix},
$$
lo que corresponde a rotar $\mathbf{x}$ 90º hacia arriba.

In [ ]:
# Matriz de rotación
A = np.array([[0, -1],
              [1, 0]])
x = np.array([1, 0])

# Transformación
T_x = np.dot(A, x)
print("Transformación de x:", T_x)

Transformación de x: [0 1]


### Transformación Lineal de Escalado

Un ejemplo sencillo de escalado en $\mathbb{R}^2$ es la siguiente transformación lineal:

$$
T(\mathbf{x}) = A \mathbf{x} = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix} \begin{bmatrix} 1 \\ 1 \end{bmatrix} = \begin{bmatrix} 2 \\ 3 \end{bmatrix},
$$

Aquí, el vector original $\mathbf{x} = \begin{bmatrix} 1 \\ 1 \end{bmatrix}$ se escala multiplicando su componente $x$ por 2 y su componente $y$ por 3, obteniendo el vector $\begin{bmatrix} 2 \\ 3 \end{bmatrix}$.

***

### Transformación Lineal de Proyección

Consideremos la proyección ortogonal sobre el eje $x$ en $\mathbb{R}^2$, que "aplasta" el vector sobre ese eje eliminando la componente vertical:

$$
T(\mathbf{v}) = P \mathbf{v} = \begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} x \\ 0 \end{bmatrix}.
$$

Por ejemplo, proyectando $\mathbf{v} = \begin{bmatrix} 3 \\ 5 \end{bmatrix}$, obtenemos:

$$
T\left(\begin{bmatrix} 3 \\ 5 \end{bmatrix}\right) = \begin{bmatrix} 3 \\ 0 \end{bmatrix}.
$$

***

### Transformación Lineal de Reflexión

La reflexión respecto al eje $x$ cambia el signo de la componente $y$ manteniendo la de $x$. La matriz asociada es:

$$
T(\mathbf{w}) = R \mathbf{w} = \begin{bmatrix} 1 & 0 \\ 0 & -1 \end{bmatrix} \begin{bmatrix} 3 \\ 4 \end{bmatrix} = \begin{bmatrix} 3 \\ -4 \end{bmatrix}.
$$

Aquí, el vector $\mathbf{w}$ se refleja respecto al eje $x$ invirtiendo su componente vertical.

---
