<a href="https://colab.research.google.com/github/financieras/math_for_ai/blob/main/220_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Ejemplo del taxista
[Hoja de cálculo](https://docs.google.com/spreadsheets/d/1RHwkhmq2qKMV5LIjMt43g0VHawsT6M0-rjk0UhjqsC4/edit?usp=sharing)

Deseamos conocer la facturación que raliza un taxi en cuatro carreras en las que ha realizado estos kilometrajes: 10, 4, 25, 20.

Sabemos que:
1. Por bajada de bander se cobra 2.5 euros
2. Por kilómetro recorrido se cobra 1.3 euros

La ecuación para calcular el importe de una carrera de taxi es una línea recta:
$$y = 2,5 + 1,3 x$$

donde:
- $x$ son los kilómetros recorridos
- $y$ es el importe de la carrera, lo que se ha de pagar

Al compararlo con el producto matricial que se hace un perceptrón al multiplicar la matriz de pesos $W$ por los valores de la variable independiente $X$, se añade un 1 correspondiente al **bias** o sesgo. Así la recta puede verse como:

$$y = 1 \cdot 2,5 + 1,3 \cdot x$$

Podemos resolverlo de forma matricial, para lo cual necesitamos añadir una columna de unos a la matriz $W$.

$$Y = W \cdot X$$

$$Y = \begin{bmatrix}
1 & 10 \\
1 & 4 \\
1 & 25 \\
1 & 20
\end{bmatrix}_{4 \times 2}
\begin{bmatrix}
2.5 \\
1.3
\end{bmatrix}_{2 \times 1}
=
\begin{bmatrix}
15.5 \\
7.7 \\
35 \\
28.5
\end{bmatrix}_{4 \times 1}$$

Para calcular la facturación total simplemente sumamos los importes de estas cuatro carreras.

Facturación Total = 15,5 + 7,7 + 35+ 28,5 = 86,7 €.

In [18]:
import numpy as np

# Definir el array con los kilómetros recorridos por el taxi en 4 carreras
X = np.array([10, 4, 25, 20])

# Ampliar X añadiendo una fila de unos
X_ampliado = np.vstack([np.ones(X.shape), X])

# Definir los pesos, subida de bandera y precio por kilómetro recorrido
W = np.array([2.5, 1.3])

# Multiplicamos las dos matrices
# Calcular el vector: Importes facturados en cada carrera
importes = np.dot(W, X_ampliado)

print("X_ampliado:")
print(X_ampliado)
print("\nVector: Importes facturados en cada carrera")
print(importes)
print("\nTotal Facturado:")
print(np.sum(importes))


X_ampliado:
[[ 1.  1.  1.  1.]
 [10.  4. 25. 20.]]

Vector: Importes facturados en cada carrera
[15.5  7.7 35.  28.5]

Total Facturado:
86.7


In [23]:
# Si multiplicamos usando la W Transpuesta no da error ya que Numpy es flexible
# Además el resultado que se obtiene es idéntico. Numpy se encarga de encajar las dimensiones
np.dot(W, X_ampliado)

array([15.5,  7.7, 35. , 28.5])