# Conceptos fundamentales de matrices

## 1. Definición de matriz

Una matriz es una estructura rectangular de datos ordenados en filas y columnas. Matemáticamente, una matriz se puede representar como:

$$A = \begin{pmatrix} 
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{pmatrix}$$

Donde:
- $a_{ij}$ representa el elemento ubicado en la fila $i$ y columna $j$.
- $m$ es el número de filas.
- $n$ es el número de columnas.
- La matriz anterior es de dimensión  $ m \times n $, con $m$ filas y $n$ columnas.

En Python, podemos representar matrices utilizando la biblioteca NumPy:

In [1]:
import numpy as np

# Crear una matriz de 3x3
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matriz A:")
print(A)

Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Acceder a los elementos de una matriz
En Python podemos acceder a elementos específicos de una matriz utilizando índices.

In [2]:
# Accediendo a elementos de la matriz
print(f"Elemento A[0,0]: {A[0,0]}")  # Equivalente a a_{11}
print(f"Elemento A[1,2]: {A[1,2]}")  # Equivalente a a_{23}

# Obteniendo dimensiones
filas, columnas = A.shape
print(f"Dimensiones de A: {filas}×{columnas}")
print(f"Número total de elementos: {A.size}")

Elemento A[0,0]: 1
Elemento A[1,2]: 6
Dimensiones de A: 3×3
Número total de elementos: 9


### Submatrices
Una submatriz es una porción de una matriz original.  
En Python, podemos extraer submatrices utilizando el sistema de indexación de NumPy:

In [3]:
# Extraer una submatriz (las primeras 2 filas y 2 columnas)
submatriz = A[0:2, 0:2]
print("Submatriz de A (primeras 2 filas y columnas):")
print(submatriz)

Submatriz de A (primeras 2 filas y columnas):
[[1 2]
 [4 5]]


## 2. Tipos de Matrices

Existen varios tipos de matrices según su estructura o propiedades:

1. **Matriz cuadrada**: $m = n$ (mismo número de filas y columnas).
2. **Matriz fila**: $m = 1$ (una sola fila).
3. **Matriz columna**: n = 1 (una sola columna).
4. **Matriz nula**: Todos sus elementos son 0.
5. **Matriz identidad**: Matriz cuadrada con 1s en la diagonal principal y 0s fuera de ella, denotada $I$.
6. **Matriz diagonal**: Solo tiene elementos en la diagonal principal.

### Ejemplos

$$
I_3 = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}$$
$$
\text{Matriz nula } 2\times2 = \begin{bmatrix}
0 & 0 \\
0 & 0
\end{bmatrix}
$$

In [4]:
# Matriz cuadrada 3x3
cuadrada = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print("Matriz cuadrada 3x3:")
print(cuadrada)

# Matriz identidad 3x3
identidad = np.eye(3)
print("\nMatriz identidad 3x3:")
print(identidad)

# Matriz fila y columna
fila = np.array([[1, 2, 3]])
columna = np.array([[4], [5], [6]])
print("\nMatriz fila (1x3):")
print(fila)
print("\nMatriz columna (3x1):")
print(columna)

# Matriz nula 2x2
nula = np.zeros((2, 2))
print("\nMatriz nula 2x2:")
print(nula)

Matriz cuadrada 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz identidad 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz fila (1x3):
[[1 2 3]]

Matriz columna (3x1):
[[4]
 [5]
 [6]]

Matriz nula 2x2:
[[0. 0.]
 [0. 0.]]


## 3. Operaciones Básicas con Matrices

### Suma y Resta
Dos matrices $A$ y $B$ de las mismas dimensiones se suman/restan elemento a elemento:
$$
C = A + B, \quad c_{ij} = a_{ij} + b_{ij}
$$

### Multiplicación por Escalar
Un escalar $k$ multiplica cada elemento de la matriz:
$$
C = kA, \quad c_{ij} = k \cdot a_{ij}
$$

In [5]:
# Definimos dos matrices 2x2
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Suma
suma = A + B
print("Suma A + B:")
print(suma)

# Resta
resta = A - B
print("\nResta A - B:")
print(resta)

# Multiplicación por escalar (normalización simple)
k = 0.5
escalada = k * A
print("\nMultiplicación de A por escalar 0.5:")
print(escalada)

Suma A + B:
[[ 6  8]
 [10 12]]

Resta A - B:
[[-4 -4]
 [-4 -4]]

Multiplicación de A por escalar 0.5:
[[0.5 1. ]
 [1.5 2. ]]


## 4. Combinación Lineal

Una **combinación lineal** de vectores $ \mathbf{v_1}, \mathbf{v_2}, \ldots, \mathbf{v_n} $ es:
$$
\mathbf{w} = c_1 \mathbf{v_1} + c_2 \mathbf{v_2} + \cdots + c_n \mathbf{v_n}
$$
El espacio generado es el conjunto de todas las combinaciones lineales.

### Ejemplo
Para $ \mathbf{v_1} = [1, 0] $, $ \mathbf{v_2} = [0, 1] $:
$$
\mathbf{w} = 2 \mathbf{v_1} + 3 \mathbf{v_2} = [2, 3]
$$

In [6]:
# Vectores base
v1 = np.array([1, 0])
v2 = np.array([0, 1])

# Combinación lineal
w = 2 * v1 + 3 * v2
print("Combinación lineal w:", w)

Combinación lineal w: [2 3]


## 5. Interpolación lineal con matrices
Sí tiene sentido este concepto en ciertos contextos, pero no en el sentido tradicional de interpolación entre puntos individuales.  
En el caso, la interpolación lineal con matrices puede interpretarse como una aproximación o transición entre dos matrices mediante una combinación lineal.  
Esto se utiliza en aplicaciones como animaciones, gráficos computacionales y transformaciones geométricas.

### Interpolación lineal entre matrices:
Dadas dos matrices $A$ y $B$ del mismo tamaño, la interpolación lineal se define como:
$$
M(t) = (1 - t)A + tB
$$
donde:
- $t \in[0, 1]$ es el parámetro de interpolación.
- $M(t)$ es la matriz interpolada para un valor específico de $t$.

### Propiedades:
1. Cuando $t = 0 \Rightarrow M(t) = A$.
2. Cuando $t = 1 \Rightarrow M(t) = B$.
3. Para valores intermedios de $t$, $M(t)$ es una combinación ponderada de las dos matrices.

### Aplicaciones:
- **Gráficos computacionales**: Para transiciones suaves entre transformaciones representadas por matrices.
- **Modelado físico**: En simulaciones donde se necesita interpolar entre estados representados por matrices.
- **Interpolación de datos tabulados**: Si los datos están organizados en forma matricial, se puede aplicar interpolación línea a cada entrada.

Es importante que las matrices involucradas tengan las mismas dimensiones para que la operación esté definida.

In [7]:
import numpy as np

# Definimos las matrices A y B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Función para interpolación lineal entre matrices
def interpolate_matrices(A, B, t):
    """
    Interpolación lineal entre dos matrices A y B.
    t: parámetro de interpolación (0 <= t <= 1)
    """
    return (1 - t) * A + t * B

# Ejemplo: Interpolamos para diferentes valores de t
t_values = [0, 0.25, 0.5, 0.75, 1]  # Valores de t entre 0 y 1

print("Interpolación lineal entre las matrices A y B:")
for t in t_values:
    M_t = interpolate_matrices(A, B, t)
    print(f"\nPara t = {t}:")
    print(M_t)


Interpolación lineal entre las matrices A y B:

Para t = 0:
[[1 2]
 [3 4]]

Para t = 0.25:
[[2. 3.]
 [4. 5.]]

Para t = 0.5:
[[3. 4.]
 [5. 6.]]

Para t = 0.75:
[[4. 5.]
 [6. 7.]]

Para t = 1:
[[5 6]
 [7 8]]


## 5. Multiplicación de Matrices

La multiplicación de matrices $A$ (de $m \times p $) y $ B $ (de $p \times n$) produce una matriz $C$ de $m \times n$). El elemento $c_{ij}$ se calcula como:
$$
c_{ij} = \sum_{k=1}^{p} a_{ik} \cdot b_{kj}
$$

### Condición
Las columnas de $A$ deben igualar las filas de $B$.

### Aplicación en Deep Learning
- Capas lineales: $W \cdot X$, donde $W$ es la matriz de pesos y $X$ el vector de entrada.

### Ejemplo
$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad
B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}, \quad
A \cdot B = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}
$$


In [8]:
# Matrices 2x2
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Multiplicación
C = np.dot(A, B)  # o A @ B
print("Multiplicación A · B:")
print(C)

# Ejemplo Deep Learning: Capa lineal
X = np.array([[0.1], [0.2]])  # Entrada (2 características)
W = np.array([[0.5, 0.3],     # Pesos (2 entradas, 2 salidas)
              [0.4, 0.6]])
salida = np.dot(W, X)
print("\nSalida de capa lineal W · X:")
print(salida)

Multiplicación A · B:
[[19 22]
 [43 50]]

Salida de capa lineal W · X:
[[0.11]
 [0.16]]


## 6. Transpuesta de una Matriz

La **transpuesta** de una matriz $A$, denotada $A^T$, intercambia filas por columnas:
$$
(A^T)_{ij} = A_{ji}
$$

### Propiedades
- $(A^T)^T = A$
- $(A + B)^T = A^T + B^T$

### Ejemplo
$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}, \quad
A^T = \begin{bmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \end{bmatrix}
$$

In [9]:
# Matriz 3x2
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Transpuesta
A_T = A.T  # o np.transpose(A)
print("Matriz A:")
print(A)
print("\nTranspuesta A^T:")
print(A_T)

# Ejemplo en IA: Producto X^T · X
X = np.array([[0.1, 0.5],
              [0.2, 0.3]])
X_T = X.T
resultado = np.dot(X_T, X)
print("\nProducto X^T · X (covarianza aproximada):")
print(resultado)

Matriz A:
[[1 2]
 [3 4]
 [5 6]]

Transpuesta A^T:
[[1 3 5]
 [2 4 6]]

Producto X^T · X (covarianza aproximada):
[[0.05 0.11]
 [0.11 0.34]]


## 7. Producto Escalar (de Vectores)

El **producto escalar** entre dos vectores $ \mathbf{u} $ y $ \mathbf{v} $ de igual longitud $ n $ se define como:

$$
\mathbf{u} \cdot \mathbf{v} = u_1 v_1 + u_2 v_2 + \cdots + u_n v_n = \sum_{i=1}^{n} u_i v_i
$$

En términos de matrices, si $ \mathbf{u} $ es un vector fila ($ 1 \times n $) y $ \mathbf{v} $ es un vector columna ($ n \times 1 $), el producto escalar es $ \mathbf{u} \cdot \mathbf{v} $.

### Propiedades
- Conmutativa: $ \mathbf{u} \cdot \mathbf{v} = \mathbf{v} \cdot \mathbf{u} $.
- Distributiva: $ \mathbf{u} \cdot (\mathbf{v} + \mathbf{w}) = \mathbf{u} \cdot \mathbf{v} + \mathbf{u} \cdot \mathbf{w} $.

### Ejemplo
Para $ \mathbf{u} = [1, 2, 3] $ y $ \mathbf{v} = [4, 5, 6] $:
$$
\mathbf{u} \cdot \mathbf{v} = 1 \cdot 4 + 2 \cdot 5 + 3 \cdot 6 = 4 + 10 + 18 = 32
$$

In [10]:
import numpy as np

# Vectores
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Producto escalar
producto_escalar = np.dot(u, v)
print("Producto escalar: u · v =", producto_escalar)

Producto escalar: u · v = 32


## 8. Norma de un Vector y de una Matriz

La **norma** mide la "longitud" o "magnitud" de un vector o matriz.

### Norma de un Vector
La norma más común es la norma euclidiana (L2):
$$
||\mathbf{u}|| = \sqrt{u_1^2 + u_2^2 + \cdots + u_n^2} = \sqrt{\sum_{i=1}^{n} u_i^2}
$$

### Norma de una Matriz
La norma de Frobenius de una matriz $ A $ es:
$$
||A||_F = \sqrt{\sum_{i=1}^{m} \sum_{j=1}^{n} a_{ij}^2}
$$

### Ejemplo
- Vector $ \mathbf{u} = [3, 4] $:
$$
||\mathbf{u}|| = \sqrt{3^2 + 4^2} = \sqrt{25} = 5
$$
- Matriz $ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $:
$$
||A||_F = \sqrt{1^2 + 2^2 + 3^2 + 4^2} = \sqrt{30} \approx 5.477
$$

In [11]:
# Norma de un vector
u = np.array([3, 4])
norma_u = np.linalg.norm(u)
print("Norma de u:")
print(norma_u)

# Norma de Frobenius de una matriz
A = np.array([[1, 2],
              [3, 4]])
norma_A = np.linalg.norm(A)
print("\nNorma de Frobenius de A:")
print(norma_A)

Norma de u:
5.0

Norma de Frobenius de A:
5.477225575051661


## 9. Coseno de Similitud

El **coseno** entre dos vectores $ \mathbf{u} $ y $ \mathbf{v} $ mide el ángulo entre ellos:
$$
\cos(\theta) = \frac{\mathbf{u} \cdot \mathbf{v}}{||\mathbf{u}|| \cdot ||\mathbf{v}||}
$$

### Interpretación
- $ \cos(\theta) = 1 $: Vectores paralelos en la misma dirección.
- $ \cos(\theta) = 0 $: Vectores perpendiculares.
- $ \cos(\theta) = -1 $: Vectores en direcciones opuestas.

### Ejemplo
Para $ \mathbf{u} = [1, 0] $ y $ \mathbf{v} = [0, 1] $:
$$
\cos(\theta) = \frac{1 \cdot 0 + 0 \cdot 1}{\sqrt{1^2 + 0^2} \cdot \sqrt{0^2 + 1^2}} = \frac{0}{1 \cdot 1} = 0
$$

In [12]:
# Vectores
u = np.array([1, 0])
v = np.array([0, 1])

# Coseno
coseno = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
print("Coseno entre u y v:")
print(coseno)

Coseno entre u y v:
0.0


## 10. Producto cruz
El **producto cruz** (o producto vectorial) de dos vectores $\mathbf{u}$ y $\mathbf{v}$ en $\mathbb{R}^3$ produce un vector perpendicular a ambos. Se denota como $\mathbf{u} \times \mathbf{v}$ y se define como:

$$
\mathbf{u} \times \mathbf{v} = (u_y v_z - u_z v_y, u_z v_x - u_x v_z, u_x v_y - u_y v_x)
$$

Donde $\mathbf{u} = (u_x, u_y, u_z)$ y $\mathbf{v} = (v_x, v_y, v_z)$.

### Propiedades
- El resultado es ortogonal a $\mathbf{u}$ y $\mathbf{v}$.
- Su magnitud es $||\mathbf{u} \times \mathbf{v}|| = ||\mathbf{u}|| ||\mathbf{v}|| \sin(\theta)$, donde $\theta$ es el ángulo entre los vectores.
- Es anticommutativo: $\mathbf{u} \times \mathbf{v} = -(\mathbf{v} \times \mathbf{u})$.

### Fórmula matricial
Puede calcularse como el determinante de una matriz:

$$
\mathbf{u} \times \mathbf{v} = \det \begin{bmatrix} \mathbf{i} & \mathbf{j} & \mathbf{k} \\ u_x & u_y & u_z \\ v_x & v_y & v_z \end{bmatrix}
$$

Donde $\mathbf{i}, \mathbf{j}, \mathbf{k}$ son los vectores unitarios en $x, y, z$.

---

## Ejemplo resuelto

Calculemos $\mathbf{u} \times \mathbf{v}$ para:

- $\mathbf{u} = (1, 2, 3)$
- $\mathbf{v} = (4, 5, 6)$

### Cálculo manual
Usamos la fórmula:

$$
\mathbf{u} \times \mathbf{v} = (u_y v_z - u_z v_y, u_z v_x - u_x v_z, u_x v_y - u_y v_x)
$$

- Componente $x$: $u_y v_z - u_z v_y = 2 \cdot 6 - 3 \cdot 5 = 12 - 15 = -3$
- Componente $y$: $u_z v_x - u_x v_z = 3 \cdot 4 - 1 \cdot 6 = 12 - 6 = 6$
- Componente $z$: $u_x v_y - u_y v_x = 1 \cdot 5 - 2 \cdot 4 = 5 - 8 = -3$

Resultado: $\mathbf{u} \times \mathbf{v} = (-3, 6, -3)$

**Verificación**

El vector $[-3, 6, -3]$ es perpendicular a $\mathbf{u}$ y $\mathbf{v}$. Podemos confirmarlo con el producto escalar:

- $\mathbf{u} \cdot (\mathbf{u} \times \mathbf{v}) = 1 \cdot (-3) + 2 \cdot 6 + 3 \cdot (-3) = -3 + 12 - 9 = 0$
- $\mathbf{v} \cdot (\mathbf{u} \times \mathbf{v}) = 4 \cdot (-3) + 5 \cdot 6 + 6 \cdot (-3) = -12 + 30 - 18 = 0$

Ambos son 0, lo que confirma la ortogonalidad.

In [13]:
import numpy as np

# Definimos los vectores
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Producto cruz con NumPy
resultado = np.cross(u, v)

print("Producto cruz u × v:", resultado)

Producto cruz u × v: [-3  6 -3]


## 11. Traza de una Matriz

La **traza** de una matriz cuadrada $ A $ de orden $ n \times n $ es la suma de los elementos de su diagonal principal:
$$
\text{tr}(A) = a_{11} + a_{22} + \cdots + a_{nn} = \sum_{i=1}^{n} a_{ii}
$$

### Ejemplo
Para $ A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} $:
$$
\text{tr}(A) = 1 + 5 + 9 = 15
$$

In [14]:
# Matriz cuadrada
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Traza
traza = np.trace(A)
print("Traza de A:")
print(traza)

Traza de A:
15


## 12. Determinante

El **determinante** de una matriz cuadrada mide su "volumen" o si es invertible. Para una matriz $ 2 \times 2 $:
$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}, \quad \det(A) = ad - bc
$$

### Ejemplo
Para $ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $:
$$
\det(A) = 1 \cdot 4 - 2 \cdot 3 = 4 - 6 = -2
$$

In [15]:
# Matriz 2x2
A = np.array([[1, 2],
              [3, 4]])

# Determinante
det = np.linalg.det(A)
print("Determinante de A:")
print(det)

Determinante de A:
-2.0000000000000004


## 13. Matriz Inversa

La **inversa** de una matriz cuadrada $ A $, denotada $ A^{-1} $, satisface:
$$
A \cdot A^{-1} = I
$$
Existe si $ \det(A) \neq 0 $. Para $ 2 \times 2 $:
$$
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}, \quad A^{-1} = \frac{1}{\det(A)} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

### Ejemplo
Para $ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $:
$$
A^{-1} = \frac{1}{-2} \begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix} = \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}
$$

Comprobación de que $A \cdot A^{-1} = I$

$$
A \cdot A^{-1} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \cdot \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} = I
$$


In [16]:
# Matriz 2x2
A = np.array([[1, 2],
              [3, 4]])

# Inversa
A_inv = np.linalg.inv(A)
print("Inversa de A:")
print(A_inv)

# Verificación: A · A^-1 = I
print("\nVerificación A · A^(-1):")
resultado = np.dot(A, A_inv)
print(resultado)
print()

# Redondeamos a 10 decimales
resultado_redondeado = np.round(resultado, decimals=10)

print("Resultado de A · A^(-1) (redondeado):")
print(resultado_redondeado)

Inversa de A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Verificación A · A^(-1):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Resultado de A · A^(-1) (redondeado):
[[1. 0.]
 [0. 1.]]


## 14. Sistemas de Ecuaciones Lineales

Un sistema de ecuaciones lineales se escribe como $ A \mathbf{x} = \mathbf{b} $, donde $ A $ es la matriz de coeficientes, $ \mathbf{x} $ el vector de incógnitas y $ \mathbf{b} $ el vector de términos independientes.

### Ejemplo
$$
\begin{cases}
2x + 3y = 8 \\
x - y = 1
\end{cases}
$$
En forma matricial:
$$
\begin{bmatrix} 2 & 3 \\ 1 & -1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 8 \\ 1 \end{bmatrix}
$$

Solución con inversa: $$ \mathbf{x} = A^{-1} \cdot \mathbf{b} $$

**_Demostración_**

Partimos de la expresión matricial del sistema de ecuaciones y queremos despejar $\mathbf{x}$:

$$ A \mathbf{x} = \mathbf{b} $$

Premultiplicamos por la inversa de $A$ en ambos lados de la ecuación:

$$ A^{-1} \cdot A \cdot \mathbf{x} = A^{-1} \cdot \mathbf{b} $$

Sabemos que la inversa de $A$ por $A$ es la matriz identidad $I$.

$ A^{-1} \cdot A = I$

Nos ha quedado lo siguiente:

$$ I \cdot \mathbf{x} = A^{-1} \cdot \mathbf{b} $$

También sabemos que la matriz identidad $I$ por $\mathbf{x}$ es igual a $\mathbf{x}$.

$ I \cdot \mathbf{x} = x$

Con esto ya hemos conseguido despejar $\mathbf{x}$:

$$ \mathbf{x} = A^{-1} \cdot \mathbf{b} $$

In [17]:
# Matriz de coeficientes y vector b
A = np.array([[2, 3],
              [1, -1]])
b = np.array([8, 1])

# Solución
#x = np.linalg.solve(A, b)  # o mejor con np.dot(np.linalg.inv(A), b)
x = np.dot(np.linalg.inv(A), b)

print("Solución x, y:")
print(x)

Solución x, y:
[2.2 1.2]


## 15. Forma Escalonada y Reducción

La **forma escalonada** de una matriz se obtiene aplicando eliminación gaussiana. Una matriz está en forma escalonada si:
- Las filas no nulas están sobre las filas de ceros.
- El primer elemento no nulo de cada fila (pivote) está a la derecha del pivote de la fila anterior.

### Ejemplo
Matriz $ A = \begin{bmatrix} 1 & 2 & 3 \\ 2 & 4 & 5 \end{bmatrix} $ se reduce a:
$$
\begin{bmatrix} 1 & 2 & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

Nota:  
NumPy no tiene una función directa para forma escalonada; usamos eliminación manual o bibliotecas como SymPy para ejemplos básicos

In [18]:
# Usamos SymPy para reducción
from sympy import Matrix

A = Matrix([[1, 2, 3],
            [2, 4, 5]])
escalonada, _ = A.rref()
print("Forma escalonada de A:")
print(np.array(escalonada))

Forma escalonada de A:
[[1 2 0]
 [0 0 1]]


In [19]:
A = Matrix([[1, 1, 1, 3],
            [1, 2, 3, 0],
            [1, 3, 4, -2]])
escalonada, _ = A.rref()
print("Forma escalonada de A:")
print(np.array(escalonada))

Forma escalonada de A:
[[1 0 0 5]
 [0 1 0 -1]
 [0 0 1 -1]]


## 16. Rango de una Matriz

El **rango** de una matriz es el número de filas o columnas linealmente independientes, equivalente al número de pivotes en su forma escalonada.

### Ejemplo
Para $ A = \begin{bmatrix} 1 & 2 \\ 2 & 4 \end{bmatrix} $, la forma escalonada es:
$$
\begin{bmatrix} 1 & 2 \\ 0 & 0 \end{bmatrix}
$$
Rango = 1.

In [20]:
# Matriz
A = np.array([[1, 2],
              [2, 4]])

# Rango
rango = np.linalg.matrix_rank(A)
print("Rango de A:", rango)

Rango de A: 1


## 17. Transformaciones Lineales

Una matriz $ A $ define una transformación lineal $ T(\mathbf{x}) = A \mathbf{x} $. Ejemplo: Rotación, escalado.

### Ejemplo
Rotación 90° en 2D:
$$
A = \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}, \quad T\left(\begin{bmatrix} 1 \\ 0 \end{bmatrix}\right) = \begin{bmatrix} 0 \\ 1 \end{bmatrix}
$$

In [21]:
# Matriz de rotación
A = np.array([[0, -1],
              [1, 0]])
x = np.array([1, 0])

# Transformación
T_x = np.dot(A, x)
print("Transformación de x:", T_x)

Transformación de x: [0 1]
